In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.figure_factory as ff
import plotly.express as px

In [2]:
matches = pd.read_csv('seasonwise/matches_all_seasons.csv')

In [3]:
matches.head(10)

,MatchRow,TossTeam,HomeTeamName,AwayTeamName,1Summary,FirstBattingTeamName,RevisedOver,RevisedTarget,2Summary,SecondBattingTeamName,...,MatchName1,MatchName2,Winner,WinDetails,Runs1,Wickets1,Overs1,Runs2,Wickets2,Overs2
0,59.0,Rajasthan Royals,Chennai Super Kings,Rajasthan Royals,163/5 (20 Overs),Chennai Super Kings,0.0,0.0,164/7 (20 Overs),Rajasthan Royals,...,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,won by 3 wickets,163.0,5.0,20.0,164.0,7.0,20.0
1,58.0,Punjab Kings,Chennai Super Kings,Punjab Kings,112/8 (20 Overs),Punjab Kings,0.0,0.0,116/1 (14.5 Overs),Chennai Super Kings,...,Chennai Super Kings,Punjab Kings,Chennai Super Kings,won by 9 wickets,112.0,8.0,20.0,116.0,1.0,14.5
2,57.0,Rajasthan Royals,Delhi Capitals,Rajasthan Royals,192/9 (20 Overs),Rajasthan Royals,0.0,0.0,87/10 (16.1 Overs),Delhi Capitals,...,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,won by 105 runs,192.0,9.0,20.0,87.0,10.0,16.1
3,56.0,Rajasthan Royals,Punjab Kings,Rajasthan Royals,221/3 (20 Overs),Punjab Kings,0.0,0.0,180/7 (20 Overs),Rajasthan Royals,...,Punjab Kings,Rajasthan Royals,Punjab Kings,won by 41 runs,221.0,3.0,20.0,180.0,7.0,20.0
4,55.0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,122/9 (18 Overs),Royal Challengers Bangalore,0.0,0.0,126/1 (16 Overs),Mumbai Indians,...,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,won by 9 wickets,122.0,9.0,18.0,126.0,1.0,16.0
5,54.0,Chennai Super Kings,Deccan Chargers,Chennai Super Kings,147/8 (20 Overs),Deccan Chargers,0.0,0.0,148/3 (19.2 Overs),Chennai Super Kings,...,Deccan Chargers,Chennai Super Kings,Chennai Super Kings,won by 7 wickets,147.0,8.0,20.0,148.0,3.0,19.2
6,53.0,Mumbai Indians,Rajasthan Royals,Mumbai Indians,145/7 (20 Overs),Mumbai Indians,0.0,0.0,146/5 (20 Overs),Rajasthan Royals,...,Rajasthan Royals,Mumbai Indians,Rajasthan Royals,won by 5 wickets,145.0,7.0,20.0,146.0,5.0,20.0
7,52.0,Punjab Kings,Kolkata Knight Riders,Punjab Kings,174/6 (20 Overs),Punjab Kings,0.0,0.0,175/7 (19.4 Overs),Kolkata Knight Riders,...,Kolkata Knight Riders,Punjab Kings,Kolkata Knight Riders,won by 3 wickets,174.0,6.0,20.0,175.0,7.0,19.4
8,51.0,Royal Challengers Bangalore,Deccan Chargers,Royal Challengers Bangalore,165/10 (20 Overs),Deccan Chargers,0.0,0.0,171/5 (19 Overs),Royal Challengers Bangalore,...,Deccan Chargers,Royal Challengers Bangalore,Royal Challengers Bangalore,won by 5 wickets,165.0,10.0,20.0,171.0,5.0,19.0
9,50.0,Mumbai Indians,Delhi Capitals,Mumbai Indians,180/8 (20 Overs),Mumbai Indians,0.0,0.0,179/5 (19.5 Overs),Delhi Capitals,...,Delhi Capitals,Mumbai Indians,Delhi Capitals,won by 5 wickets,180.0,8.0,20.0,179.0,5.0,19.5

In [4]:
matches.isnull().sum()

MatchRow                      0
TossTeam                      0
HomeTeamName                  0
AwayTeamName                  0
1Summary                      8
FirstBattingTeamName          0
RevisedOver                   0
RevisedTarget                 0
2Summary                     11
SecondBattingTeamName         0
GroundName                   45
city                          0
MATCH_COMMENCE_START_DATE     0
MatchTime                     0
MatchEndDate                  0
MatchEndTime                  0
Year                          0
MatchName1                    0
MatchName2                    0
Winner                       13
WinDetails                    0
Runs1                         8
Wickets1                      8
Overs1                        8
Runs2                        11
Wickets2                     11
Overs2                       11
dtype: int64

In [5]:
matches['1Summary'].fillna('Not Available',inplace=True)

In [6]:
matches['2Summary'].fillna('Not Available',inplace=True)

In [7]:
matches[matches['GroundName'].isnull()]

,MatchRow,TossTeam,HomeTeamName,AwayTeamName,1Summary,FirstBattingTeamName,RevisedOver,RevisedTarget,2Summary,SecondBattingTeamName,...,MatchName1,MatchName2,Winner,WinDetails,Runs1,Wickets1,Overs1,Runs2,Wickets2,Overs2
71,47.0,Mumbai Indians,Chennai Super Kings,Mumbai Indians,147/5 (20 Overs),Mumbai Indians,0.0,0.0,151/3 (19.1 Overs),Chennai Super Kings,...,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,won by 7 wickets,147.0,5.0,20.0,151.0,3.0,19.1
80,38.0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,157/2 (20 Overs),Mumbai Indians,0.0,0.0,141/7 (20 Overs),Royal Challengers Bangalore,...,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,won by 16 runs,157.0,2.0,20.0,141.0,7.0,20.0
91,27.0,Kolkata Knight Riders,Punjab Kings,Kolkata Knight Riders,153/3 (20 Overs),Kolkata Knight Riders,0.0,0.0,154/4 (20 Overs),Punjab Kings,...,Punjab Kings,Kolkata Knight Riders,Punjab Kings,won by 6 wickets,153.0,3.0,20.0,154.0,4.0,20.0
93,25.0,Rajasthan Royals,Deccan Chargers,Rajasthan Royals,141/5 (20 Overs),Deccan Chargers,0.0,0.0,142/7 (19.4 Overs),Rajasthan Royals,...,Deccan Chargers,Rajasthan Royals,Rajasthan Royals,won by 3 wickets,141.0,5.0,20.0,142.0,7.0,19.4
101,17.0,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians,187/6 (20 Overs),Mumbai Indians,0.0,0.0,95/9 (15.2 Overs),Kolkata Knight Riders,...,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,won by 92 runs,187.0,6.0,20.0,95.0,9.0,15.2
104,14.0,Delhi Capitals,Royal Challengers Bangalore,Delhi Capitals,149/7 (20 Overs),Royal Challengers Bangalore,0.0,0.0,150/4 (19.2 Overs),Delhi Capitals,...,Royal Challengers Bangalore,Delhi Capitals,Delhi Capitals,won by 6 wickets,149.0,7.0,20.0,150.0,4.0,19.2
113,5.0,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings,179/5 (20 Overs),Chennai Super Kings,0.0,0.0,87/10 (15.2 Overs),Royal Challengers Bangalore,...,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,won by 92 runs,179.0,5.0,20.0,87.0,10.0,15.2
255,72.0,Kolkata Knight Riders,Delhi Capitals,Kolkata Knight Riders,162/4 (20 Overs),Kolkata Knight Riders,0.0,0.0,144/8 (20 Overs),Delhi Capitals,...,Delhi Capitals,Kolkata Knight Riders,Kolkata Knight Riders,won by 18 runs,162.0,4.0,20.0,144.0,8.0,20.0
258,69.0,Kolkata Knight Riders,Pune Warriors India,Kolkata Knight Riders,136/4 (20 Overs),Kolkata Knight Riders,0.0,0.0,102/8 (20 Overs),Pune Warriors India,...,Pune Warriors India,Kolkata Knight Riders,Kolkata Knight Riders,won by 34 runs,136.0,4.0,20.0,102.0,8.0,20.0
271,56.0,Royal Challengers Bangalore,Pune Warriors India,Royal Challengers Bangalore,173/3 (20 Overs),Royal Challengers Bangalore,0.0,0.0,138/9 (20 Overs),Pune Warriors India,...,Pune Warriors India,Royal Challengers Bangalore,Royal Challengers Bangalore,won by 35 runs,173.0,3.0,20.0,138.0,9.0,20.0
276,51.0,Rajasthan Royals,Pune Warriors India,Rajasthan Royals,125/6 (20 Overs),Pune Warriors India,0.0,0.0,126/3 (16.2 Overs),Rajasthan Royals,...,Pune Warriors India,Rajasthan Royals,Rajasthan Royals,won by 7 wickets,125.0,6.0,20.0,126.0,3.0,16.2
283,44.0,Mumbai Indians,Pune Warriors India,Mumbai Indians,120/9 (20 Overs),Mumbai Indians,0.0,0.0,119/6 (20 Overs),Pune Warriors India,...,Pune Warriors India,Mumbai Indians,Mumbai Indians,won by 1 run,120.0,9.0,20.0,119.0,6.0,20.0
293,34.0,Deccan Chargers,Pune Warriors India,Deccan Chargers,177/4 (20 Overs),Deccan Chargers,0.0,0.0,159/7 (20 Overs),Pune Warriors India,...,Pune Warriors India,Deccan Chargers,Deccan Chargers,won by 18 runs,177.0,4.0,20.0,159.0,7.0,20.0
297,30.0,Delhi Capitals,Pune Warriors India,Delhi Capitals,146/2 (20 Overs),Pune Warriors India,0.0,0.0,148/2 (16 Overs),Delhi Capitals,...,Pune Warriors India,Delhi Capitals,Delhi Capitals,won by 8 wickets,146.0,2.0,20.0,148.0,2.0,16.0
311,16.0,Chennai Super Kings,Pune Warriors India,Chennai Super Kings,155/5 (20 Overs),Chennai Super Kings,0.0,0.0,156/3 (19.2 Overs),Pune Warriors India,...,Pune Warriors India,Chennai Super Kings,Pune Warriors India,won by 7 wickets,155.0,5.0,20.0,156.0,3.0,19.2
319,8.0,Punjab Kings,Pune Warriors India,Punjab Kings,166/6 (20 Overs),Pune Warriors India,0.0,0.0,144/8 (20 Overs),Punjab Kings,...,Pune Warriors India,Punjab Kings,Pune Warriors India,won by 22 runs,166.0,6.0,20.0,144.0,8.0,20.0
332,71.0,Delhi Capitals,Pune Warriors India,Delhi Capitals,172/5 (20 Overs),Pune Warriors India,0.0,0.0,134/9 (20 Overs),Delhi Capitals,...,Pune Warriors India,Delhi Capitals,Pune Warriors India,won by 38 runs,172.0,5.0,20.0,134.0,9.0,20.0
345,58.0,Mumbai Indians,Pune Warriors India,Mumbai Indians,112/8 (20 Overs),Pune Warriors India,0.0,0.0,116/5 (18.5 Overs),Mumbai Indians,...,Pune Warriors India,Mumbai Indians,Mumbai Indians,won by 5 wickets,112.0,8.0,20.0,116.0,5.0,18.5
347,56.0,Kolkata Knight Riders,Pune Warriors India,Kolkata Knight Riders,152/6 (20 Overs),Kolkata Knight Riders,0.0,0.0,106/10 (19.3 Overs),Pune Warriors India,...,Pune Warriors India,Kolkata Knight Riders,Kolkata Knight Riders,won by 46 runs,152.0,6.0,20.0,106.0,10.0,19.3
357,46.0,Royal Challengers Bangalore,Pune Warriors India,Royal Challengers Bangalore,187/3 (20 Overs),Royal Challengers Bangalore,0.0,0.0,170/9 (20 Overs),Pune Warriors India,...,Pune Warriors India,Royal Challengers Bangalore,Royal Challengers Bangalore,won by 17 runs,187.0,3.0,20.0,170.0,9.0,20.0
361,42.0,Chennai Super Kings,Pune Warriors India,Chennai Super Kings,164/3 (20 Overs),Chennai Super Kings,0.0,0.0,127/9 (20 Overs),Pune Warriors India,...,Pune Warriors India,Chennai Super Kings,Chennai Super Kings,won by 37 runs,164.0,3.0,20.0,127.0,9.0,20.0
381,22.0,Sunrisers Hyderabad,Pune Warriors India,Sunrisers Hyderabad,119/8 (20 Overs),Sunrisers Hyderabad,0.0,0.0,108/10 (19 Overs),Pune Warriors India,...,Pune Warriors India,Sunrisers Hyderabad,Sunrisers Hyderabad,won by 11 runs,119.0,8.0,20.0,108.0,10.0,19.0
390,13.0,Rajasthan Royals,Pune Warriors India,Rajasthan Royals,145/5 (20 Overs),Rajasthan Royals,0.0,0.0,148/3 (18.4 Overs),Pune Warriors India,...,Pune Warriors India,Rajasthan Royals,Pune Warriors India,won by 7 wickets,145.0,5.0,20.0,148.0,3.0,18.4
397,6.0,Punjab Kings,Pune Warriors India,Punjab Kings,99/9 (20 Overs),Pune Warriors India,0.0,0.0,100/2 (12.2 Overs),Punjab Kings,...,Pune Warriors India,Punjab Kings,Punjab Kings,won by 8 wickets,99.0,9.0,20.0,100.0,2.0,12.2
465,58.0,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,180/4 (20 Overs),Royal Challengers Bangalore,0.0,0.0,109/10 (19 Overs),Rajasthan Royals,...,Royal Challengers Bangalore,Rajasthan Royals,Royal Challengers Bangalore,won by 71 runs,180.0,4.0,20.0,109.0,10.0,19.0
509,14.0,Kolkata Knight Riders,Punjab Kings,Kolkata Knight Riders,155/9 (20 Overs),Punjab Kings,0.0,0.0,159/6 (17.5 Overs),Kolkata Knight Riders,...,Punjab Kings,Kolkata Knight Riders,Kolkata Knight Riders,won by 4 wickets,155.0,9.0,20.0,159.0,6.0,17.5
513,10.0,Delhi Capitals,Punjab Kings,Delhi Capitals,165/7 (20 Overs),Punjab Kings,0.0,0.0,169/5 (19.5 Overs),Delhi Capitals,...,Punjab Kings,Delhi Capitals,Delhi Capitals,won by 5 wickets,165.0,7.0,20.0,169.0,5.0,19.5
520,3.0,Rajasthan Royals,Punjab Kings,Rajasthan Royals,162/7 (20 Overs),Rajasthan Royals,0.0,0.0,136/8 (20 Overs),Punjab Kings,...,Punjab Kings,Rajasthan Royals,Rajasthan Royals,won by 26 runs,162.0,7.0,20.0,136.0,8.0,20.0
554,29.0,Mumbai Indians,Rising Pune Supergiant,Mumbai Indians,159/5 (20 Overs),Rising Pune Supergiant,0.0,0.0,161/2 (18.3 Overs),Mumbai Indians,...,Rising Pune Supergiant,Mumbai Indians,Mumbai Indians,won by 8 wickets,159.0,5.0,20.0,161.0,2.0,18.3
558,25.0,Gujarat Lions,Rising Pune Supergiant,Gujarat Lions,195/3 (20 Overs),Rising Pune Supergiant,0.0,0.0,196/7 (20 Overs),Gujarat Lions,...,Rising Pune Supergiant,Gujarat Lions,Gujarat Lions,won by 3 wickets,195.0,3.0,20.0,196.0,7.0,20.0
563,20.0,Kolkata Knight Riders,Rising Pune Supergiant,Kolkata Knight Riders,160/5 (20 Overs),Rising Pune Supergiant,0.0,0.0,162/8 (19.3 Overs),Kolkata Knight Riders,...,Rising Pune Supergiant,Kolkata Knight Riders,Kolkata Knight Riders,won by 2 wickets,160.0,5.0,20.0,162.0,8.0,19.3
567,16.0,Royal Challengers Bangalore,Rising Pune Supergiant,Royal Challengers Bangalore,185/3 (20 Overs),Royal Challengers Bangalore,0.0,0.0,172/8 (20 Overs),Rising Pune Supergiant,...,Rising Pune Supergiant,Royal Challengers Bangalore,Royal Challengers Bangalore,won by 13 runs,185.0,3.0,20.0,172.0,8.0,20.0
588,55.0,Punjab Kings,Rising Pune Supergiant,Punjab Kings,73/10 (15.5 Overs),Punjab Kings,0.0,0.0,78/1 (12 Overs),Rising Pune Supergiant,...,Rising Pune Supergiant,Punjab Kings,Rising Pune Supergiant,won by 9 wickets,73.0,10.0,15.5,78.0,1.0,12.0
604,39.0,Gujarat Lions,Rising Pune Supergiant,Gujarat Lions,161/10 (19.5 Overs),Gujarat Lions,0.0,0.0,167/5 (19.5 Overs),Rising Pune Supergiant,...,Rising Pune Supergiant,Gujarat Lions,Rising Pune Supergiant,won by 5 wickets,161.0,10.0,19.5,167.0,5.0,19.5
609,34.0,Royal Challengers Bangalore,Rising Pune Supergiant,Royal Challengers Bangalore,157/3 (20 Overs),Rising Pune Supergiant,0.0,0.0,96/9 (20 Overs),Royal Challengers Bangalore,...,Rising Pune Supergiant,Royal Challengers Bangalore,Rising Pune Supergiant,won by 61 runs,157.0,3.0,20.0,96.0,9.0,20.0
613,30.0,Kolkata Knight Riders,Rising Pune Supergiant,Kolkata Knight Riders,182/5 (20 Overs),Rising Pune Supergiant,0.0,0.0,184/3 (18.1 Overs),Kolkata Knight Riders,...,Rising Pune Supergiant,Kolkata Knight Riders,Kolkata Knight Riders,won by 7 wickets,182.0,5.0,20.0,184.0,3.0,18.1
619,24.0,Sunrisers Hyderabad,Rising Pune Supergiant,Sunrisers Hyderabad,176/3 (20 Overs),Sunrisers Hyderabad,0.0,0.0,179/4 (20 Overs),Rising Pune Supergiant,...,Rising Pune Supergiant,Sunrisers Hyderabad,Rising Pune Supergiant,won by 6 wickets,176.0,3.0,20.0,179.0,4.0,20.0
634,9.0,Delhi Capitals,Rising Pune Supergiant,Delhi Capitals,205/4 (20 Overs),Delhi Capitals,0.0,0.0,108/10 (16.1 Overs),Rising Pune Supergiant,...,Rising Pune Supergiant,Delhi Capitals,Delhi Capitals,won by 97 runs,205.0,4.0,20.0,108.0,10.0,16.1
641,2.0,Mumbai Indians,Rising Pune Supergiant,Mumbai Indians,184/8 (20 Overs),Mumbai Indians,0.0,0.0,187/3 (19.5 Overs),Rising Pune Supergiant,...,Rising Pune Supergiant,Mumbai Indians,Rising Pune Supergiant,won by 7 wickets,184.0,8.0,20.0,187.0,3.0,19.5
647,56.0,Punjab Kings,Chennai Super Kings,Punjab Kings,153/10 (19.4 Overs),Punjab Kings,0.0,0.0,159/5 (19.1 Overs),Chennai Super Kings,...,Chennai Super Kings,Punjab Kings,Chennai Super Kings,won by 5 wickets,153.0,10.0,19.4,159.0,5.0,19.1
657,46.0,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,179/4 (20 Overs),Sunrisers Hyderabad,0.0,0.0,180/2 (19 Overs),Chennai Super Kings,...,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings,won by 8 wickets,179.0,4.0,20.0,180.0,2.0,19.0
668,35.0,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,127/9 (20 Overs),Royal Challengers Bangalore,0.0,0.0,128/4 (18 Overs),Chennai Super Kings,...,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings,won by 6 wickets,127.0,9.0,20.0,128.0,4.0,18.0
673,30.0,Delhi Capitals,Chennai Super Kings,Delhi Capitals,211/4 (20 Overs),Chennai Super Kings,0.0,0.0,198/5 (20 Overs),Delhi Capitals,...,Chennai Super Kings,Delhi Capitals,Chennai Super Kings,won by 13 runs,211.0,4.0,20.0,198.0,5.0,20.0
676,27.0,Mumbai Indians,Chennai Super Kings,Mumbai Indians,169/5 (20 Overs),Chennai Super Kings,0.0,0.0,170/2 (19.4 Overs),Mumbai Indians,...,Chennai Super Kings,Mumbai Indians,Mumbai Indians,won by 8 wickets,169.0,5.0,20.0,170.0,2.0,19.4
686,17.0,Rajasthan Royals,Chennai Super Kings,Rajasthan Royals,204/5 (20 Overs),Chennai Super Kings,0.0,0.0,140/10 (18.3 Overs),Rajasthan Royals,...,Chennai Super Kings,Rajasthan Royals,Chennai Super Kings,won by 64 runs,204.0,5.0,20.0,140.0,10.0,18.3

In [8]:
matches['GroundName'].fillna('Not Available',inplace=True)

In [9]:
matches[matches['Winner'].isnull()]

,MatchRow,TossTeam,HomeTeamName,AwayTeamName,1Summary,FirstBattingTeamName,RevisedOver,RevisedTarget,2Summary,SecondBattingTeamName,...,MatchName1,MatchName2,Winner,WinDetails,Runs1,Wickets1,Overs1,Runs2,Wickets2,Overs2
12,47.0,Kolkata Knight Riders,Delhi Capitals,Kolkata Knight Riders,Not Available,Delhi Capitals,0.0,0.0,Not Available,Kolkata Knight Riders,...,Delhi Capitals,Kolkata Knight Riders,NaN,Match abandoned without a ball bowled,NaN,NaN,NaN,NaN,NaN,NaN
105,13.0,Kolkata Knight Riders,Chennai Super Kings,Kolkata Knight Riders,Not Available,Chennai Super Kings,0.0,0.0,Not Available,Kolkata Knight Riders,...,Chennai Super Kings,Kolkata Knight Riders,NaN,Match abandoned without a ball bowled,NaN,NaN,NaN,NaN,NaN,NaN
111,7.0,Rajasthan Royals,Mumbai Indians,Rajasthan Royals,Not Available,Mumbai Indians,0.0,0.0,Not Available,Rajasthan Royals,...,Mumbai Indians,Rajasthan Royals,NaN,Match abandoned without a ball bowled,NaN,NaN,NaN,NaN,NaN,NaN
184,68.0,Pune Warriors India,Delhi Capitals,Pune Warriors India,56/3 (10.1 Overs),Delhi Capitals,0.0,0.0,Not Available,Pune Warriors India,...,Delhi Capitals,Pune Warriors India,NaN,No result,56.0,3.0,10.1,NaN,NaN,NaN
232,20.0,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,Not Available,Royal Challengers Bangalore,0.0,0.0,Not Available,Rajasthan Royals,...,Royal Challengers Bangalore,Rajasthan Royals,NaN,Match abandoned without a ball bowled,NaN,NaN,NaN,NaN,NaN,NaN
294,33.0,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings,Not Available,Chennai Super Kings,0.0,0.0,Not Available,Royal Challengers Bangalore,...,Royal Challengers Bangalore,Chennai Super Kings,NaN,Match abandoned without a ball bowled,NaN,NaN,NaN,NaN,NaN,NaN
296,31.0,Deccan Chargers,Kolkata Knight Riders,Deccan Chargers,Not Available,Kolkata Knight Riders,0.0,0.0,Not Available,Deccan Chargers,...,Kolkata Knight Riders,Deccan Chargers,NaN,Match abandoned without a ball bowled,NaN,NaN,NaN,NaN,NaN,NaN
468,55.0,Delhi Capitals,Royal Challengers Bangalore,Delhi Capitals,187/5 (20 Overs),Delhi Capitals,0.0,0.0,2/0 (1.1 Overs),Royal Challengers Bangalore,...,Royal Challengers Bangalore,Delhi Capitals,NaN,No result,187.0,5.0,20.0,2.0,0.0,1.1
494,29.0,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,200/7 (20 Overs),Royal Challengers Bangalore,0.0,0.0,Not Available,Rajasthan Royals,...,Royal Challengers Bangalore,Rajasthan Royals,NaN,No result,200.0,7.0,20.0,NaN,NaN,NaN
498,25.0,Rajasthan Royals,Kolkata Knight Riders,Rajasthan Royals,Not Available,Kolkata Knight Riders,0.0,0.0,Not Available,Rajasthan Royals,...,Kolkata Knight Riders,Rajasthan Royals,NaN,Match abandoned without a ball bowled,NaN,NaN,NaN,NaN,NaN,NaN
614,29.0,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,Not Available,Royal Challengers Bangalore,0.0,0.0,Not Available,Sunrisers Hyderabad,...,Royal Challengers Bangalore,Sunrisers Hyderabad,NaN,Match abandoned without a ball bowled,NaN,NaN,NaN,NaN,NaN,NaN
714,49.0,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,62/7 (5 Overs),Royal Challengers Bangalore,0.0,0.0,41/1 (3.2 Overs),Rajasthan Royals,...,Royal Challengers Bangalore,Rajasthan Royals,NaN,No result,62.0,7.0,5.0,41.0,1.0,3.2
986,45.0,Chennai Super Kings,Lucknow Super Giants,Chennai Super Kings,125/7 (19.2 Overs),Lucknow Super Giants,0.0,0.0,Not Available,Chennai Super Kings,...,Lucknow Super Giants,Chennai Super Kings,NaN,No result,125.0,7.0,19.2,NaN,NaN,NaN

In [10]:
matches['Winner'].fillna('Not Available',inplace=True)

In [11]:
for column in ['Runs1','Wickets1','Overs1','Runs2','Wickets2','Overs2']:
    matches[column].fillna(-1,inplace=True)

In [12]:
cat_col = []
num_col = []
for column in matches.columns:
    if matches[column].dtype != 'object':
        num_col.append(column)
    else:
        cat_col.append(column)

In [13]:
cat_col

['TossTeam',
 'HomeTeamName',
 'AwayTeamName',
 '1Summary',
 'FirstBattingTeamName',
 '2Summary',
 'SecondBattingTeamName',
 'GroundName',
 'city',
 'MATCH_COMMENCE_START_DATE',
 'MatchTime',
 'MatchEndDate',
 'MatchEndTime',
 'MatchName1',
 'MatchName2',
 'Winner',
 'WinDetails']

In [14]:
num_col

['MatchRow',
 'RevisedOver',
 'RevisedTarget',
 'Year',
 'Runs1',
 'Wickets1',
 'Overs1',
 'Runs2',
 'Wickets2',
 'Overs2']

In [15]:
matches[matches['GroundName'] == 'OUTSource Oval']

Empty DataFrame
Columns: [MatchRow, TossTeam, HomeTeamName, AwayTeamName, 1Summary, FirstBattingTeamName, RevisedOver, RevisedTarget, 2Summary, SecondBattingTeamName, GroundName, city, MATCH_COMMENCE_START_DATE, MatchTime, MatchEndDate, MatchEndTime, Year, MatchName1, MatchName2, Winner, WinDetails, Runs1, Wickets1, Overs1, Runs2, Wickets2, Overs2]
Index: []

[0 rows x 27 columns]

In [16]:
sorted(matches['GroundName'].unique())

['ACA-VDCA Stadium',
 'Arun Jaitley Stadium',
 'Barabati Stadium',
 'Barsapara Cricket Stadium',
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
 'Brabourne - CCI',
 'Brabourne Stadium',
 'Buffalo Park',
 'DY Patil Stadium',
 'De Beers Diamond Oval',
 'Dubai International Cricket Stadium',
 'Dubai International Stadium',
 'Eden Gardens',
 'Green Park',
 'HPCA Stadium',
 'Himachal Pradesh Cricket Association Stadium',
 'Holkar Cricket Stadium',
 'IS Bindra Stadium',
 'JSCA International Cricket Stadium',
 'Jawaharlal Nehru Stadium',
 'Kingsmead',
 'M Chinnaswamy Stadium',
 'M. A. Chidambaram Stadium',
 'M. Chinnaswamy Stadium',
 'MA Chidambaram Stadium',
 'Maharashtra Cricket Association Stadium',
 'Narendra Modi Stadium',
 'New Wanderers Stadium',
 'Newlands',
 'Not Available',
 'OUTsurance Oval',
 'Punjab Cricket Association IS Bindra Stadium',
 'Rajiv Gandhi International Stadium',
 'Rajiv Gandhi Intl. Cricket Stadium',
 'Saurashtra Cricket Association Stadium',
 'Sawai Mansingh Stadium',
 'Shaheed Veer Narayan Singh International Cricket Stadium',
 'Sharjah Cricket Stadium',
 'Sheikh Zayed Cricket Stadium',
 'SuperSport Park',
 'Vidarbha Cricket Association Stadium',
 'Wankhede Stadium',
 'Zayed Cricket Stadium']

In [17]:
def ground_name(name):
    grounds = {
        'Brabourne - CCI' : 'Brabourne Stadium',
        'Dubai International Stadium' : 'Dubai International Cricket Stadium',
        'HPCA Stadium' : 'Himachal Pradesh Cricket Association Stadium',
        'MA Chidambaram Stadium' : 'M. A. Chidambaram Stadium',
        'OUTsurance Oval' : 'Mangaung Oval',
        'IS Bindra Stadium' : 'Punjab Cricket Association IS Bindra Stadium',
        'Rajiv Gandhi Intl. Cricket Stadium' : 'Rajiv Gandhi International Stadium'
    }
    
    if name not in grounds.keys():
        return name
    else:
        return grounds[name]

In [18]:
matches['GroundName'] = matches['GroundName'].apply(ground_name)

In [19]:
matches[matches['Overs2'] == -1]

,MatchRow,TossTeam,HomeTeamName,AwayTeamName,1Summary,FirstBattingTeamName,RevisedOver,RevisedTarget,2Summary,SecondBattingTeamName,...,MatchName1,MatchName2,Winner,WinDetails,Runs1,Wickets1,Overs1,Runs2,Wickets2,Overs2
12,47.0,Kolkata Knight Riders,Delhi Capitals,Kolkata Knight Riders,Not Available,Delhi Capitals,0.0,0.0,Not Available,Kolkata Knight Riders,...,Delhi Capitals,Kolkata Knight Riders,Not Available,Match abandoned without a ball bowled,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
105,13.0,Kolkata Knight Riders,Chennai Super Kings,Kolkata Knight Riders,Not Available,Chennai Super Kings,0.0,0.0,Not Available,Kolkata Knight Riders,...,Chennai Super Kings,Kolkata Knight Riders,Not Available,Match abandoned without a ball bowled,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
111,7.0,Rajasthan Royals,Mumbai Indians,Rajasthan Royals,Not Available,Mumbai Indians,0.0,0.0,Not Available,Rajasthan Royals,...,Mumbai Indians,Rajasthan Royals,Not Available,Match abandoned without a ball bowled,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
184,68.0,Pune Warriors India,Delhi Capitals,Pune Warriors India,56/3 (10.1 Overs),Delhi Capitals,0.0,0.0,Not Available,Pune Warriors India,...,Delhi Capitals,Pune Warriors India,Not Available,No result,56.0,3.0,10.1,-1.0,-1.0,-1.0
232,20.0,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,Not Available,Royal Challengers Bangalore,0.0,0.0,Not Available,Rajasthan Royals,...,Royal Challengers Bangalore,Rajasthan Royals,Not Available,Match abandoned without a ball bowled,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
294,33.0,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings,Not Available,Chennai Super Kings,0.0,0.0,Not Available,Royal Challengers Bangalore,...,Royal Challengers Bangalore,Chennai Super Kings,Not Available,Match abandoned without a ball bowled,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
296,31.0,Deccan Chargers,Kolkata Knight Riders,Deccan Chargers,Not Available,Kolkata Knight Riders,0.0,0.0,Not Available,Deccan Chargers,...,Kolkata Knight Riders,Deccan Chargers,Not Available,Match abandoned without a ball bowled,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
494,29.0,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,200/7 (20 Overs),Royal Challengers Bangalore,0.0,0.0,Not Available,Rajasthan Royals,...,Royal Challengers Bangalore,Rajasthan Royals,Not Available,No result,200.0,7.0,20.0,-1.0,-1.0,-1.0
498,25.0,Rajasthan Royals,Kolkata Knight Riders,Rajasthan Royals,Not Available,Kolkata Knight Riders,0.0,0.0,Not Available,Rajasthan Royals,...,Kolkata Knight Riders,Rajasthan Royals,Not Available,Match abandoned without a ball bowled,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
614,29.0,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,Not Available,Royal Challengers Bangalore,0.0,0.0,Not Available,Sunrisers Hyderabad,...,Royal Challengers Bangalore,Sunrisers Hyderabad,Not Available,Match abandoned without a ball bowled,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
986,45.0,Chennai Super Kings,Lucknow Super Giants,Chennai Super Kings,125/7 (19.2 Overs),Lucknow Super Giants,0.0,0.0,Not Available,Chennai Super Kings,...,Lucknow Super Giants,Chennai Super Kings,Not Available,No result,125.0,7.0,19.2,-1.0,-1.0,-1.0

In [20]:
matches.to_csv('seasonwise/matches_all_time.csv',index=False)

# Checking null values in points_table

In [21]:
points_table = pd.read_csv('seasonwise/points_table_all_seasons.csv')

In [22]:
points_table.isnull().sum()

TeamName       0
Matches        0
Wins           0
Loss           0
Tied           0
NoResult       0
Points         0
Draw           0
ForTeams       0
AgainstTeam    0
NetRunRate     0
IsQualified    0
Performance    0
Standings      0
Year           0
dtype: int64

In [23]:
cat_col = []
num_col = []
for column in points_table.columns:
    if points_table[column].dtype != 'object':
        num_col.append(column)
    else:
        cat_col.append(column)

In [24]:
cat_col

['TeamName', 'ForTeams', 'AgainstTeam', 'Performance']

In [25]:
num_col

['Matches',
 'Wins',
 'Loss',
 'Tied',
 'NoResult',
 'Points',
 'Draw',
 'NetRunRate',
 'IsQualified',
 'Standings',
 'Year']

In [26]:
points_table['Draw'].describe()

count    136.0
mean       0.0
std        0.0
min        0.0
25%        0.0
50%        0.0
75%        0.0
max        0.0
Name: Draw, dtype: float64

In [27]:
points_table['Draw']

0      0
1      0
2      0
3      0
4      0
      ..
131    0
132    0
133    0
134    0
135    0
Name: Draw, Length: 136, dtype: int64

In [28]:
points_table.to_csv('seasonwise/points_table_all_time.csv',index=False)

## Removing null values from player_data

In [29]:
player_stats = pd.read_csv('seasonwise/for_all_seasons_2.csv')

In [30]:
player_stats.isnull().sum()

Name                    0
PlayerDOB               0
TotalRuns               0
Balls                   0
StrikeRate              0
Fours                   0
Sixes                   0
Outs                    0
NotOuts                 0
FiftyPlusRuns           0
Centuries               0
HighestScore            0
BattingAverage         56
Nation                  0
BattingStyle            0
TotalRunsConceded       0
DotBallsBowled          0
BowlingAverage          0
BowlingStrikeRate       0
EconomyRate             0
OversBowled             0
FoursConceded           0
SixesConceded           0
Wickets                 0
Maidens                 0
FourWickets             0
FiveWickets             0
BallsBowled             0
TeamCode                0
TeamName                0
Innings                 0
Matches                 0
Nationality             0
RightHandedBat          0
Year                    0
Age                     0
IsNotDismissed          0
BestBowlingWickets      0
BestBowlingRuns         0
BestScore             255
dtype: int64

In [31]:
player_stats[player_stats['BattingAverage'].isnull()][['Name','TotalRuns']]

                        Name  TotalRuns
2374          Mohammad Shami          0
2375             T Natarajan          0
2376           Khaleel Ahmed          0
2377          Jasprit Bumrah          0
2378            Ravi Bishnoi          0
2379              Yash Dayal          0
2380          Riley Meredith          0
2381             Kuldeep Sen          0
2382             Sai Kishore          0
2383             Tymal Mills          0
2384      Krishnappa Gowtham          0
2385            Basil Thampi          0
2386              Akash Deep          0
2387         Chetan Sakariya          0
2388            Nathan Ellis          0
2389        Prashant Solanki          0
2390     Matheesha Pathirana          0
2391          Sandeep Sharma          0
2392              Andrew Tye          0
2393             Varun Aaron          0
2394        Darshan Nalkande          0
2395              Anukul Roy          0
2396         Mayank Markande          0
2397        Tushar Deshpande          0
2564            Mohit Sharma          0
2565        Yuzvendra Chahal          0
2566        Tushar Deshpande          0
2567     Matheesha Pathirana          0
2568           Akash Madhwal          0
2569             Yash Thakur          0
2570      Maheesh Theekshana          0
2571           Suyash Sharma          0
2572             T Natarajan          0
2573           Khaleel Ahmed          0
2574            Rahul Chahar          0
2575              Avesh Khan          0
2576             Josh Little          0
2577           Kagiso Rabada          0
2578          Riley Meredith          0
2579            Harshit Rana          0
2580             Akash Singh          0
2581                Asif K M          0
2582  Rajvardhan Hangargekar          0
2583             Mohsin Khan          0
2584           Navdeep Saini          0
2585            Kuldip Yadav          0
2586              Yash Dayal          0
2587             Tim Southee          0
2588      Kulwant Khejroliya          0
2589            Reece Topley          0
2590            Mayank Dagar          0
2591          Sisanda Magala          0
2592        Darshan Nalkande          0
2593         Lockie Ferguson          0
2594             Duan Jansen          0
2595            Kartik Tyagi          0

In [32]:
player_stats['BattingAverage'].fillna(-1,inplace=True)

In [33]:
player_stats[(player_stats['BestScore'].isnull()) & (player_stats['TotalRuns'] == 0)]

,Name,PlayerDOB,TotalRuns,Balls,StrikeRate,Fours,Sixes,Outs,NotOuts,FiftyPlusRuns,...,Innings,Matches,Nationality,RightHandedBat,Year,Age,IsNotDismissed,BestBowlingWickets,BestBowlingRuns,BestScore
150,Shanthakumaran Sreesanth,6-2-1983,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15.0,15.0,Indian,True,2008,25,-1.0,3,29,NaN
151,Muttiah Muralitharan,17-4-1972,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15.0,15.0,Overseas,True,2008,36,-1.0,3,11,NaN
152,Palani Amarnath,1-6-1982,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,6.0,Indian,True,2008,26,-1.0,2,29,NaN
153,Gajendra Singh,10-9-1988,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,Indian,True,2008,20,-1.0,1,33,NaN
154,Daniel Vettori,27-1-1979,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,Overseas,False,2008,29,-1.0,3,15,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2591,Sisanda Magala,7-1-1991,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,Overseas,True,2023,32,-1.0,37,1,NaN
2592,Darshan Nalkande,4-10-1998,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,Indian,True,2023,25,-1.0,44,1,NaN
2593,Lockie Ferguson,13-6-1991,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,3.0,Overseas,True,2023,32,-1.0,19,1,NaN
2594,Duan Jansen,1-5-2000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,Overseas,True,2023,23,-1.0,53,1,NaN
2595,Kartik Tyagi,8-11-2000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,3.0,Indian,True,2023,23,-1.0,30,1,NaN

In [34]:
# player_stats.to_csv('seasonwise/player_stats_all_time.csv')

In [35]:
player_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2596 entries, 0 to 2595
Data columns (total 40 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                2596 non-null   object
 1   PlayerDOB           2596 non-null   object
 2   TotalRuns           2596 non-null   int64
 3   Balls               2596 non-null   float64
 4   StrikeRate          2596 non-null   float64
 5   Fours               2596 non-null   float64
 6   Sixes               2596 non-null   float64
 7   Outs                2596 non-null   float64
 8   NotOuts             2596 non-null   float64
 9   FiftyPlusRuns       2596 non-null   float64
 10  Centuries           2596 non-null   float64
 11  HighestScore        2596 non-null   int64
 12  BattingAverage      2596 non-null   object
 13  Nation              2596 non-null   object
 14  BattingStyle        2596 non-null   object
 15  TotalRunsConceded   2596 non-null   float64
 16  DotBallsBowled      2596 non-null   float64
 17  BowlingAverage      2596 non-null   float64
 18  BowlingStrikeRate   2596 non-null   float64
 19  EconomyRate         2596 non-null   float64
 20  OversBowled         2596 non-null   float64
 21  FoursConceded       2596 non-null   float64
 22  SixesConceded       2596 non-null   float64
 23  Wickets             2596 non-null   int64
 24  Maidens             2596 non-null   float64
 25  FourWickets         2596 non-null   float64
 26  FiveWickets         2596 non-null   float64
 27  BallsBowled         2596 non-null   float64
 28  TeamCode            2596 non-null   object
 29  TeamName            2596 non-null   object
 30  Innings             2596 non-null   float64
 31  Matches             2596 non-null   float64
 32  Nationality         2596 non-null   object
 33  RightHandedBat      2596 non-null   bool
 34  Year                2596 non-null   int64
 35  Age                 2596 non-null   int64
 36  IsNotDismissed      2596 non-null   float64
 37  BestBowlingWickets  2596 non-null   int64
 38  BestBowlingRuns     2596 non-null   int64
 39  BestScore           2341 non-null   object
dtypes: bool(1), float64(23), int64(7), object(9)
memory usage: 793.6+ KB

In [36]:
object_col = []
for column in player_stats.columns:
    if player_stats[column].dtype == 'object':
        object_col.append(column)

In [37]:
object_col

['Name',
 'PlayerDOB',
 'BattingAverage',
 'Nation',
 'BattingStyle',
 'TeamCode',
 'TeamName',
 'Nationality',
 'BestScore']

In [38]:
player_stats[player_stats['BattingAverage'].apply(lambda x:type(x)==float)][['Name','BattingAverage']]

Empty DataFrame
Columns: [Name, BattingAverage]
Index: []

In [39]:
player_stats['BattingAverage'] = player_stats['BattingAverage'].apply(lambda x: -1 if x == '-' else x).astype(float)

In [40]:
player_stats[player_stats['BestScore'].apply(lambda x:type(x)==str)][['Name','BestScore']]

                     Name BestScore
0             Shaun Marsh       115
1          Gautam Gambhir        86
2       Sanath Jayasuriya      114*
3            Shane Watson       76*
4            Graeme Smith        91
...                   ...       ...
2559       Mohammed Siraj        1*
2560        Yudhvir Singh         1
2561     Fazalhaq Farooqi        1*
2562         Nathan Ellis         1
2563  Varun Chakaravarthy         1

[2341 rows x 2 columns]

In [41]:
player_stats['BestScore'] = player_stats['BestScore'].apply(lambda x:'Not Available' if x is np.nan else x)

In [42]:
num_col = []
for column in player_stats.columns:
    if player_stats[column].dtype != 'object':
        num_col.append(column)

In [43]:
num_col

['TotalRuns',
 'Balls',
 'StrikeRate',
 'Fours',
 'Sixes',
 'Outs',
 'NotOuts',
 'FiftyPlusRuns',
 'Centuries',
 'HighestScore',
 'BattingAverage',
 'TotalRunsConceded',
 'DotBallsBowled',
 'BowlingAverage',
 'BowlingStrikeRate',
 'EconomyRate',
 'OversBowled',
 'FoursConceded',
 'SixesConceded',
 'Wickets',
 'Maidens',
 'FourWickets',
 'FiveWickets',
 'BallsBowled',
 'Innings',
 'Matches',
 'RightHandedBat',
 'Year',
 'Age',
 'IsNotDismissed',
 'BestBowlingWickets',
 'BestBowlingRuns']

In [44]:
player_stats[player_stats['IsNotDismissed'] == -1][['Name','TotalRuns']].sort_values('TotalRuns',ascending=False)

                          Name  TotalRuns
150   Shanthakumaran Sreesanth          0
2039              Lungi Ngidi           0
1893             Oshane Thomas          0
1894                Dale Steyn          0
1895            Arshdeep Singh          0
...                        ...        ...
999            Andrew McDonald          0
1000             Ankeet Chavan          0
1001             Ankit Rajpoot          0
1002             Bhargav Bhatt          0
2595              Kartik Tyagi          0

[255 rows x 2 columns]

In [45]:
player_stats[(player_stats['Outs'] == 0) & (player_stats['TotalRuns'] == 0)][['Name','TotalRuns','Outs','BattingAverage','HighestScore','BestScore']]

,Name,TotalRuns,Outs,BattingAverage,HighestScore,BestScore
146,Abdur Razzak,0,0.0,0.0,0,0*
149,Munaf Patel,0,0.0,0.0,0,0*
150,Shanthakumaran Sreesanth,0,0.0,0.0,-1,Not Available
151,Muttiah Muralitharan,0,0.0,0.0,-1,Not Available
152,Palani Amarnath,0,0.0,0.0,-1,Not Available
...,...,...,...,...,...,...
2591,Sisanda Magala,0,0.0,-1.0,-1,Not Available
2592,Darshan Nalkande,0,0.0,-1.0,-1,Not Available
2593,Lockie Ferguson,0,0.0,-1.0,-1,Not Available
2594,Duan Jansen,0,0.0,-1.0,-1,Not Available
2595,Kartik Tyagi,0,0.0,-1.0,-1,Not Available

In [46]:
player_stats['BattingAverage'][player_stats['Outs'] == 0] = -1

In [47]:
player_stats[(player_stats['Wickets'] == 0) & (player_stats['BallsBowled'] > 0)][['Name','BowlingAverage','Wickets']]

Empty DataFrame
Columns: [Name, BowlingAverage, Wickets]
Index: []

In [48]:
player_stats.to_csv('seasonwise/player_stats_all_time.csv',index=False)